
version: '3'
services:

  outbuild_db:
    container_name: outbuild_db
    image: postgres:16.3-alpine3.20
    restart: always
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    networks:
      - outbuild-backend

  api:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - outbuild_db
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - ./.env
    environment:
      - DB_HOST=outbuild_db
    networks:
      - outbuild-backend


networks:
  outbuild-backend:
    driver: bridge
